name: Generate Directory Listing

on:
  push:
    branches: [ main ] # Запускать при пуше в main (или master)

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate listing for 'files' directory
        uses: gacts/directory-listing@v1
        with:
          target: ./files # Твоя папка с файлами

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./files # Что публикуем

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
